services:
  db:
    container_name: mysql
    image: mysql
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: springdemo
      MYSQL_USER: Maciej
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/data/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - db
  phpmyadmin:
    container_name: phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - db
    depends_on:
      - db
  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: unless-stopped
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  db:
    driver: bridge

volumes:
  db: