server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/springdemo?allowPublicKeyRetrieval=true&useSSL=false
    username: Maciej
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000